### PR TITLE
Fix to_der crash when using Time object with generalized time

### PR DESCRIPTION
**Pull request by adfoster-r7**
Fixes a regression introduced by https://github.com/sdaubert/rasn1/commit/cb6fa343576fb20d37553fa46ce7f2623d1160b4#diff-e46f1c104156737e7ff48431864f3d1133526c88f222309f2f16891ffab1ff69R48

```
  1) RASN1::Types::GeneralizedTime#to_der generates a DER string with a Time object
     Failure/Error: utc_value = @value.new_offset('0')
     
     NoMethodError:
       undefined method `new_offset' for 2017-12-30 16:30:23 154811237190861/281474976710656 +0000:Time
     # ./lib/rasn1/types/generalized_time.rb:48:in `value_to_der'
     # ./lib/rasn1/types/base.rb:385:in `build'
     # ./lib/rasn1/types/base.rb:185:in `to_der'
     # ./spec/types/generalized_time_spec.rb:41:in `block (3 levels) in <module:Types>'
```

### CODE REVIEW

**Comment by sdaubert** [comment]
Times object should not be used with GeneralizedTime, only DateTime ones should be. There is an error in API documentation in general description of GeneralizedTime.

**Comment by adfoster-r7** [comment]
When I last researched DateTime, I believe the DateTime class was marked as deprecated:

> DateTime class is considered deprecated. Use Time class.
> https://ruby-doc.org/stdlib-3.0.0/libdoc/date/rdoc/DateTime.html

Is there benefits to using DateTime here still?

**Comment by sdaubert** [comment]
I didn't see this! I have to rewrite all GeneralizedTime class :sob:

**Comment by sdaubert** [comment]
See #32, which is more general than this PR. Will be closed soon.

**Comment by adfoster-r7** [comment]
I think the implementation would still have to support both DateTime and Time transparently - or enforce one or the other at runtime, as I believe developers normally choose between Date and DateTime at random 😄
